[package]
name = "syfala_network"
version = "0.1.0"
edition = "2024"

[dependencies]

postcard = { version = "1", default-features = false }
syfala_proto = { path = "../syfala_proto" }
oneshot = { version = "0" }
syfala_utils = { path = "../syfala_utils" }
